insert into nordpool_api.currency (id, name, symbol, decimals) values
    ('AED', 'United Arab Emirates dirham'              , 'د.إ' , 2),
    ('AFN', 'Afghan afghani'                           , '؋'   , 2),
    ('ALL', 'Albanian lek'                             , 'L'   , 2),
    ('AMD', 'Armenian dram'                            , '֏'   , 2),
    ('ANG', 'Netherlands Antillean guilder'            , 'ƒ'   , 2),
    ('AOA', 'Angolan kwanza'                           , 'Kz'  , 2),
    ('ARS', 'Argentine peso'                           , '$'   , 2),
    ('AUD', 'Australian dollar'                        , '$'   , 2),
    ('AWG', 'Aruban florin'                            , 'ƒ'   , 2),
    ('AZN', 'Azerbaijani manat'                        , '₼'   , 2),
    ('BAM', 'Bosnia and Herzegovina convertible mark'  , 'KM'  , 2),
    ('BBD', 'Barbados dollar'                          , '$'   , 2),
    ('BDT', 'Bangladeshi taka'                         , '৳'   , 2),
    ('BGN', 'Bulgarian lev'                            , 'лв'  , 2),
    ('BHD', 'Bahraini dinar'                           , '.د.ب', 3),
    ('BIF', 'Burundian franc'                          , 'FBu' , 0),
    ('BMD', 'Bermudian dollar'                         , '$'   , 2),
    ('BND', 'Brunei dollar'                            , '$'   , 2),
    ('BOB', 'Boliviano'                                , 'Bs.' , 2),
    ('BOV', 'Bolivian Mvdol (funds code)'              , 'BOV' , 2),
    ('BRL', 'Brazilian real'                           , 'R$'  , 2),
    ('BSD', 'Bahamian dollar'                          , '$'   , 2),
    ('BTN', 'Bhutanese ngultrum'                       , 'Nu.' , 2),
    ('BWP', 'Botswana pula'                            , 'P'   , 2),
    ('BYN', 'Belarusian ruble'                         , 'Br'  , 2),
    ('BZD', 'Belize dollar'                            , '$'   , 2),
    ('CAD', 'Canadian dollar'                          , '$'   , 2),
    ('CDF', 'Congolese franc'                          , 'FC'  , 2),
    ('CHE', 'WIR euro (complementary currency)'        , 'CHE' , 2),
    ('CHF', 'Swiss franc'                              , 'CHF' , 2),
    ('CHW', 'WIR franc (complementary currency)'       , 'CHW' , 2),
    ('CLF', 'Unidad de Fomento (funds code)'           , 'CLF' , 4),
    ('CLP', 'Chilean peso'                             , '$'   , 0),
    ('CNY', 'Renminbi'                                 , '¥'   , 2),
    ('COP', 'Colombian peso'                           , '$'   , 2),
    ('COU', 'Unidad de Valor Real (UVR) (funds code)'  , 'COU' , 2),
    ('CRC', 'Costa Rican colon'                        , '₡'   , 2),
    ('CUP', 'Cuban peso'                               , '$'   , 2),
    ('CVE', 'Cape Verdean escudo'                      , 'Esc' , 2),
    ('CZK', 'Czech koruna'                             , 'Kč'  , 2),
    ('DJF', 'Djiboutian franc'                         , 'Fdj' , 0),
    ('DKK', 'Danish krone'                             , 'kr'  , 2),
    ('DOP', 'Dominican peso'                           , '$'   , 2),
    ('DZD', 'Algerian dinar'                           , 'د.ج' , 2),
    ('EGP', 'Egyptian pound'                           , '£'   , 2),
    ('ERN', 'Eritrean nakfa'                           , 'Nfk' , 2),
    ('ETB', 'Ethiopian birr'                           , 'Br'  , 2),
    ('EUR', 'Euro'                                     , '€'   , 2),
    ('FJD', 'Fiji dollar'                              , '$'   , 2),
    ('FKP', 'Falkland Islands pound'                   , '£'   , 2),
    ('GBP', 'Pound sterling'                           , '£'   , 2),
    ('GEL', 'Georgian lari'                            , '₾'   , 2),
    ('GHS', 'Ghanaian cedi'                            , '₵'   , 2),
    ('GIP', 'Gibraltar pound'                          , '£'   , 2),
    ('GMD', 'Gambian dalasi'                           , 'D'   , 2),
    ('GNF', 'Guinean franc'                            , 'FG'  , 0),
    ('GTQ', 'Guatemalan quetzal'                       , 'Q'   , 2),
    ('GYD', 'Guyanese dollar'                          , '$'   , 2),
    ('HKD', 'Hong Kong dollar'                         , '$'   , 2),
    ('HNL', 'Honduran lempira'                         , 'L'   , 2),
    ('HTG', 'Haitian gourde'                           , 'G'   , 2),
    ('HUF', 'Hungarian forint'                         , 'Ft'  , 2),
    ('IDR', 'Indonesian rupiah'                        , 'Rp'  , 2),
    ('ILS', 'Israeli new shekel'                       , '₪'   , 2),
    ('INR', 'Indian rupee'                             , '₹'   , 2),
    ('IQD', 'Iraqi dinar'                              , 'ع.د' , 3),
    ('IRR', 'Iranian rial'                             , '﷼'   , 2),
    ('ISK', 'Icelandic króna (plural: krónur)'         , 'kr'  , 0),
    ('JMD', 'Jamaican dollar'                          , '$'   , 2),
    ('JOD', 'Jordanian dinar'                          , 'د.ا' , 3),
    ('JPY', 'Japanese yen'                             , '¥'   , 0),
    ('KES', 'Kenyan shilling'                          , 'Sh'  , 2),
    ('KGS', 'Kyrgyzstani som'                          , 'сом' , 2),
    ('KHR', 'Cambodian riel'                           , '៛'   , 2),
    ('KMF', 'Comoro franc'                             , 'CF'  , 0),
    ('KPW', 'North Korean won'                         , '₩'   , 2),
    ('KRW', 'South Korean won'                         , '₩'   , 0),
    ('KWD', 'Kuwaiti dinar'                            , 'د.ك' , 3),
    ('KYD', 'Cayman Islands dollar'                    , '$'   , 2),
    ('KZT', 'Kazakhstani tenge'                        , '₸'   , 2),
    ('LAK', 'Lao kip'                                  , '₭'   , 2),
    ('LBP', 'Lebanese pound'                           , 'ل.ل' , 2),
    ('LKR', 'Sri Lankan rupee'                         , 'Rs'  , 2),
    ('LRD', 'Liberian dollar'                          , '$'   , 2),
    ('LSL', 'Lesotho loti'                             , 'L'   , 2),
    ('LYD', 'Libyan dinar'                             , 'ل.د' , 3),
    ('MAD', 'Moroccan dirham'                          , 'د.م.', 2),
    ('MDL', 'Moldovan leu'                             , 'L'   , 2),
    ('MGA', 'Malagasy ariary'                          , 'Ar'  , 2),
    ('MKD', 'Macedonian denar'                         , 'ден' , 2),
    ('MMK', 'Myanmar kyat'                             , 'K'   , 2),
    ('MNT', 'Mongolian tögrög'                         , '₮'   , 2),
    ('MOP', 'Macanese pataca'                          , 'P'   , 2),
    ('MRU', 'Mauritanian ouguiya'                      , 'UM'  , 2),
    ('MUR', 'Mauritian rupee'                          , '₨'  , 2),
    ('MVR', 'Maldivian rufiyaa'                        , 'Rf'  , 2),
    ('MWK', 'Malawian kwacha'                          , 'MK'  , 2),
    ('MXN', 'Mexican peso'                             , '$'   , 2),
    ('MXV', 'Mexican Unidad de Inversion (UDI)'        , 'MXV' , 2),
    ('MYR', 'Malaysian ringgit'                        , 'RM'  , 2),
    ('MZN', 'Mozambican metical'                       , 'MT'  , 2),
    ('NAD', 'Namibian dollar'                          , '$'   , 2),
    ('NGN', 'Nigerian naira'                           , '₦'   , 2),
    ('NIO', 'Nicaraguan córdoba'                       , 'C$'  , 2),
    ('NOK', 'Norwegian krone'                          , 'kr'  , 2),
    ('NPR', 'Nepalese rupee'                           , '₨'  , 2),
    ('NZD', 'New Zealand dollar'                       , '$'   , 2),
    ('OMR', 'Omani rial'                               , 'ر.ع.', 3),
    ('PAB', 'Panamanian balboa'                        , 'B/.' , 2),
    ('PEN', 'Peruvian sol'                             , 'S/'  , 2),
    ('PGK', 'Papua New Guinean kina'                   , 'K'   , 2),
    ('PHP', 'Philippine peso'                          , '₱'   , 2),
    ('PKR', 'Pakistani rupee'                          , '₨'  , 2),
    ('PLN', 'Polish złoty'                             , 'zł'  , 2),
    ('PYG', 'Paraguayan guaraní'                       , '₲'   , 0),
    ('QAR', 'Qatari riyal'                             , 'ر.ق' , 2),
    ('RON', 'Romanian leu'                             , 'lei' , 2),
    ('RSD', 'Serbian dinar'                            , 'дин.', 2),
    ('RUB', 'Russian ruble'                            , '₽'   , 2),
    ('RWF', 'Rwandan franc'                            , 'FRw' , 0),
    ('SAR', 'Saudi riyal'                              , 'ر.س' , 2),
    ('SBD', 'Solomon Islands dollar'                   , '$'   , 2),
    ('SCR', 'Seychelles rupee'                         , '₨'  , 2),
    ('SDG', 'Sudanese pound'                           , 'ج.س.', 2),
    ('SEK', 'Swedish krona (plural: kronor)'           , 'kr'  , 2),
    ('SGD', 'Singapore dollar'                         , '$'   , 2),
    ('SHP', 'Saint Helena pound'                       , '£'   , 2),
    ('SLL', 'Sierra Leonean leone'                     , 'Le'  , 2),
    ('SOS', 'Somali shilling'                          , 'Sh'  , 2),
    ('SRD', 'Surinamese dollar'                        , '$'   , 2),
    ('SSP', 'South Sudanese pound'                     , '£'   , 2),
    ('STN', 'São Tomé and Príncipe dobra'              , 'Db'  , 2),
    ('SVC', 'Salvadoran colón'                         , '$'   , 2),
    ('SYP', 'Syrian pound'                             , '£'   , 2),
    ('SZL', 'Eswatini lilangeni'                       , 'L'   , 2),
    ('THB', 'Thai baht'                                , '฿'   , 2),
    ('TJS', 'Tajikistani somoni'                       , 'ЅМ'  , 2),
    ('TMT', 'Turkmenistani manat'                      , 'm'   , 2),
    ('TND', 'Tunisian dinar'                           , 'د.ت' , 3),
    ('TOP', 'Tongan paʻanga'                           , 'T$'  , 2),
    ('TRY', 'Turkish lira'                             , '₺'   , 2),
    ('TTD', 'Trinidad and Tobago dollar'               , '$'   , 2),
    ('TWD', 'New Taiwan dollar'                        , '$'   , 2),
    ('TZS', 'Tanzanian shilling'                       , 'Sh'  , 2),
    ('UAH', 'Ukrainian hryvnia'                        , '₴'   , 2),
    ('UGX', 'Ugandan shilling'                         , 'Sh'  , 0),
    ('USD', 'United States dollar'                     , '$'   , 2),
    ('UYI', 'Uruguay Peso en Unidades Indexadas'       , 'UYI' , 0),
    ('UYU', 'Uruguayan peso'                           , '$'   , 2),
    ('UYW', 'Unidad previsional'                       , 'UYW' , 4),
    ('UZS', 'Uzbekistani soʻm'                         , 'soʻm', 2),
    ('VED', 'Venezuelan bolívar digital'               , 'Bs.' , 2),
    ('VES', 'Venezuelan bolívar soberano'              , 'Bs.' , 2),
    ('VND', 'Vietnamese đồng'                          , '₫'   , 0),
    ('VUV', 'Vanuatu vatu'                             , 'VT'  , 0),
    ('WST', 'Samoan tala'                              , 'T'   , 2),
    ('XAF', 'CFA franc BEAC'                           , 'Fr'  , 0),
    ('XAG', 'Silver (one troy ounce)'                  , 'XAG' , 0),
    ('XAU', 'Gold (one troy ounce)'                    , 'XAU' , 0),
    ('XBA', 'European Composite Unit (EURCO)'          , 'XBA' , 0),
    ('XBB', 'European Monetary Unit (E.M.U.-6) '       , 'XBB' , 0),
    ('XBC', 'European Unit of Account 9 (E.U.A.-9)'    , 'XBC' , 0),
    ('XBD', 'European Unit of Account 17 (E.U.A.-17)'  , 'XBD' , 0),
    ('XCD', 'East Caribbean dollar'                    , '$'   , 2),
    ('XDR', 'SDR (Special Drawing Right)'              , 'XDR' , 0),
    ('XOF', 'CFA franc BCEAO'                          , 'Fr'  , 0),
    ('XPD', 'Palladium (one troy ounce)'               , 'XPD' , 0),
    ('XPF', 'CFP franc (franc Pacifique)'              , 'Fr'  , 0),
    ('XPT', 'Platinum (one troy ounce)'                , 'XPT' , 0),
    ('XSU', 'Sucre'                                    , 'XSU' , 0),
    ('XUA', 'ADB Unit of Account'                      , 'XUA' , 0),
    ('YER', 'Yemeni rial'                              , '﷼'   , 2),
    ('ZAR', 'South African rand'                       , 'R'   , 2),
    ('ZMW', 'Zambian kwacha'                           , 'ZK'  , 2),
    ('ZWL', 'Zimbabwean dollar'                        , '$'   , 2);